### ISSUE TITLE
EMACS

### ISSUE THREAD

**Issue by unhammer** [apertium/apertium-syntax-highlight#1]
Maybe links to these could go in readme or something

* https://github.com/unhammer/hfst-mode (lexc, twolc etc.)
* https://github.com/unhammer/dix (xmls)
* https://github.com/TinoDidriksen/cg3/tree/master/emacs (cg)

**Comment by mansayk** [comment]
Hi!

Added here d8f019fc642c81a938f9c650f511639e036b4482 and here 25d7a768d5f476ae14a3f19fc5f3fb197695504c

Best,
