### ISSUE TITLE
editorconfig?

### ISSUE THREAD

**Issue by flammie** [apertium/apertium-syntax-highlight#3]
Maybe a suggested editorconfig would fit here? I have:

```
[*]
end_of_line = lf
insert_final_newline = true
charset = utf-8

[*.{dix,t1x,t2x,t3x,lrx,rlx}]
indent_size = 2
trim_trailing_whitespace = true
```

**Comment by TinoDidriksen** [comment]
Yes. And `trim_trailing_whitespace = true` should be true for all files.

**Comment by flammie** [comment]
I had to move it out of * in root editorconfig because few odd formats have meaningful trailing whitespaces, especially mail or mime.

**Comment by mansayk** [comment]
Hi!

Added here bfcfb341f1387b10c2043017b7b8f8024b42415a

Best,
